digi/xbee/models/hw.py
digi/xbee/models/protocol.py

- 0x45 - XB8X
- Fixed a bug in the protocol assignation algorithm with XBee3 variants.
Signed-off-by: Diego Escalona <diego.escalona@digi.com>

hardware: add support for new hardware variants

---

digi/xbee/models/status.py

fix #3: add missing Modem Status values for Remote Manager connect and disconnect

---

digi/xbee/devices.py
digi/xbee/models/message.py
digi/xbee/reader.py
doc/user_doc/handling_analog_and_digital_io_lines.rst
functional_tests/long_test.py

Replaces all `time.clock()` calls with `time.time()`. On the the Unix platform `time.clock()` is not wall-time like it is on Windows. It results in timeouts that last orders of magnitude longer than expected on the Ubunutu 16.04 system I am working on. For instance this code was talking over an hour to finish:
```
xbee = ZigBeeDevice("/dev/ttyUSB0", 9600)
xbee.open()
xnet = xbee.get_network()
xnet.set_discovery_timeout(3.2)
xnet.start_discovery_process()
while xnet.is_discovery_running():
time.sleep(0.5)
for device in xnet.get_devices():
print(device)
print('done')
```
Also `time.clock()` is depreciated. 
My PR is very untested beyond the code I provided above as I have just begun using the lib.  So more testing is needed.

Fix timeouts on Unix platform

---

digi/xbee/devices.py
digi/xbee/packets/base.py
digi/xbee/packets/cellular.py
digi/xbee/packets/common.py
digi/xbee/packets/devicecloud.py
digi/xbee/packets/network.py
digi/xbee/packets/raw.py
digi/xbee/packets/wifi.py
digi/xbee/reader.py

- Transformed _unescape_data() method to public.
- Removed all unnecesary calls to unescape_data() from create_packet methods.
- Replaced __read_next_packet() method by a search in the xbee packet queue.
Signed-off-by: Héctor González <hector.gonzalez@digi.com>

operating_mode: fix packet reader function to correctly escape the bytes

---

digi/xbee/packets/aft.py
digi/xbee/packets/base.py
digi/xbee/packets/factory.py

fix #28: return an unknown XBee packet when the received packet is not supported by the library instead of raising an exception

---

digi/xbee/devices.py
digi/xbee/reader.py

The serial port is only closed in the XBee reader if the process has not
been stopped and the serial port is still open.

fix #23: fix a problem when closing the device connection

---

digi/xbee/devices.py
digi/xbee/packets/aft.py
digi/xbee/packets/common.py
digi/xbee/packets/factory.py

Some code related to AT commands (get, set and execute) has been
re-organized and moved to the AbstractXBeeDevice class.

fix #52: add AT Command Queue packet and use it when the apply changes flag is set to false

---

digi/xbee/reader.py

Signed-off-by: Diego Escalona <diego.escalona@digi.com>

fix #36: log error when processing a wrong frame instead of stopping the reader

---

digi/xbee/devices.py

When a message received callback has been added, `add_remote()` is led to
believe that every xbee with only a 16bit addr and no 64bit addr is unique.
This leaks one RemoteXBeeDevice worth of memory each time a packet is
received.

Fix a leak in add_remote()

---

digi/xbee/devices.py
digi/xbee/models/status.py
digi/xbee/packets/aft.py

Some of these values were added back in the 1140C release. Others in the x10 release cycle (which came out several months ago).
I also tried to start implementing the packet model for the User Data Relay (0x2D) frame (and the 0xAD output frame to go with it), but adding new API frames to the library is more complicated than I anticipated. I noticed we're also missing the 0x23 TX Request with TLS Profile frame. Docs for both of these can be found here: https://www.digi.com/resources/documentation/digidocs/PDFs/90002258.pdf

Add some missing status codes from XBee Cellular/XBee3 Cellular

---

digi/xbee/reader.py

- The stop method of the reader class now waits until the thread is fully shut-down.
In some scenarios, when the port was closed and open very quickly, a read exception
was thrown by the reader thread.
- Check thread stop variable in the read packet method to avoid accessing the port
if the thread has been already stopped.
Signed-off-by: David Escalona <david.escalona@digi.com>

reader: fix the reader stop method to avoid accessing the port when it is closed

---

digi/xbee/devices.py
digi/xbee/exception.py
digi/xbee/models/mode.py

- If the device cannot be discovered in API mode, the library checks if it is
in AT mode by entering command mode. In some scenarios like a hardware reset
or recovery mode, the module could be in API mode, but the library cannot
find it and determines that it is in AT mode raising an exception. To avoid
that, the library now asks for the actual operating mode after entering
command mode.
Signed-off-by: Diego Escalona <diego.escalona@digi.com>

devices: read the actual operating mode when the device is in AT mode

---

digi/xbee/devices.py
digi/xbee/firmware.py
digi/xbee/models/zdo.py

* remote at: check the origin of 'Remote AT command response' frames
* zdo: check the origin of 'Explicit RX indicator' frames
* firmware: use the calculated size when reading the next chunk of an ota file
* firmware: workaround for 'No ack' error on XBee 3 DigiMesh remote firmware updates

Several fixes

---

digi/xbee/devices.py
digi/xbee/firmware.py
digi/xbee/profile.py

* Retry the application of a profile settings also when receiving an at command error status
* Define different reset timeouts for local and remote XBee firmware updates (remote also depends on the protocol running on the XBee)

XBee 3 DigiMesh/802.15.4 remote profile update fix

---

digi/xbee/devices.py

DigiMesh XBee S2C and XBee 3 3001 firmware versions does not support synchronous
sleep, so 'SS' command fails because it is not included.
https://github.com/digidotcom/xbee-python/issues/103

role: catch a possible exception while determining the XBee role

---

digi/xbee/devices.py

On DigiMesh, the 16 bit address is set to 0xFFFE on the XBee frames, which is
the value returned by get_16bit_addr() method on a RemoteXBee.
On local XBee devices, however, 'None' was being returned. This commits
makes it so that 0xFFFE is also returned when using local XBee devices,
fixing this inconsistency.
Signed-off-by: Jose Diaz de Grenu <Jose.DiazdeGrenu@digi.com>

devices: digimesh: set 16bit address as unknown

---

digi/xbee/devices.py
digi/xbee/models/atcomm.py
digi/xbee/packets/aft.py
digi/xbee/packets/base.py
digi/xbee/packets/digimesh.py
digi/xbee/packets/factory.py
digi/xbee/packets/zigbee.py
digi/xbee/reader.py
doc/api/digi.xbee.packets.digimesh.rst
doc/api/digi.xbee.packets.rst

Added a method and a callback to get the Zigbee source routes and DigiMesh trace routes from local to a remote node.

Get Zigbee and DigiMesh routes

---

digi/xbee/firmware.py

When the XBee was open before starting the firmware update, the code will
try to open it again when the firmware update is done.
In order for his open operation to be successful, we need to wait for the
target to reset first.

firmware: wait for target reset before restoring updater

---

digi/xbee/firmware.py

Do not modify the current XBee baudrate when doing remote updates, because
we can not ensure a reliable serial communication for, in this case, 230400
bauds.
https://jira.digi.com/browse/DAL-2588

firmware: do not change the baudrate on a remote firmware update

---

digi/xbee/firmware.py

On remote updates, if a chunk is not sent and needs to be retransmitted,
do not ask for the next data block but use the last one.

firmware: ota: use the last block instead of the next on retries

---

digi/xbee/reader.py

This problem was causing the 'readDataFrom' method to return the first
data packet on the queue, not the first one from the given remote device.

packets_queue: fix an issue when the device's 16-bit address is unknown

---

digi/xbee/devices.py

Use the correct method to check if the generic interface is open or not,
instead of assuming it is a serial interface.

devices: use correct property to check if interface is open

---

digi/xbee/firmware.py

This commit configures the 'current time' and 'upgrade time' fields of the
'Upgrade End Response' explicit packet with the same value for an immediate
update after transferring the OTA file.
Starting from Zigbee 100A firmware versions (I guess next versions of DigiMesh
and 802.15.4 too), the OTA firmware update process supports scheduled updates.
This means the 'Upgrade End Response' explicit packet must set the
'upgrade time' to:
* the same value as 'current time' (immediate update)
* a bigger value than 'current time' (scheduled updates)
* or 0xFFFFFFFF (update delayed until another 'Upgrade End Response' is
received by the client)
https://jira.digi.com/browse/XBPL-350

firmware: ota: set 'upgrade time' with the same value as 'current time'

---

digi/xbee/devices.py

stop the get routing table and return cancel code when discover has been
canceled.

devices: return cancel status on discover cancel

---

digi/xbee/profile.py

The update status callback expects an integer percentage, so pass a 0
instead of None.
This prevents the XNM creating a status JSON with a null percentage:
{
"client-id" : "myMQTTClientID",
"request" : "profile-update",
"timeout" : 13,
"max-sleep-time" : 120,
"status" : [ {
"xpro-file" : "/etc/config/xbee-profiles/profile_1009_NI.xpro",
"node" : {
"64bit" : "0013A2004195C889",
"16bit" : "FFFE"
},
"pct" : null,
"code" : 2,
"desc" : "In progress: Reading device parameters"
} ]
}
Signed-off-by: Javier Viguera <javier.viguera@digi.com>

profile: pass integer to progress callback

---

digi/xbee/devices.py

If there was a protocol missmatch when opening the XBee object connection,
an exception was thrown but port remained open. This commit fixes this scenario
and closes the connection before throwing the exception.
Signed-off-by: David Escalona <david.escalona@digi.com>

devices: close connection when throwing protocol exception on 'open'

---

digi/xbee/devices.py
digi/xbee/filesystem.py
digi/xbee/profile.py
digi/xbee/reader.py

Python is case sensitive but XBees are not. This commit uses upper cases
to compare AT commands.

at commands: use upper case commands before comparing

---

digi/xbee/devices.py
digi/xbee/reader.py

This optional parameter may give a description of the result of the network
discovery.

discovery: add description as optional param to net discovery finished callbacks

---

digi/xbee/packets/relay.py

The local interface was not being obtained from the raw data.
Signed-off-by: Andres Saenz <andres.saenz@digi.com>

relay_frames: fix an issue when creating a User Data Relay packet

---

digi/xbee/models/accesspoint.py
digi/xbee/models/address.py
digi/xbee/models/atcomm.py
digi/xbee/models/hw.py
digi/xbee/models/info.py
digi/xbee/models/message.py
digi/xbee/models/mode.py
digi/xbee/models/options.py
digi/xbee/models/protocol.py
digi/xbee/models/status.py
digi/xbee/models/zdo.py
digi/xbee/packets/aft.py
digi/xbee/packets/base.py
digi/xbee/packets/cellular.py
digi/xbee/packets/common.py
digi/xbee/packets/devicecloud.py
digi/xbee/packets/digimesh.py
digi/xbee/packets/factory.py
digi/xbee/packets/network.py
digi/xbee/packets/raw.py
digi/xbee/packets/relay.py
digi/xbee/packets/socket.py
digi/xbee/packets/wifi.py
digi/xbee/packets/zigbee.py
digi/xbee/util/utils.py
digi/xbee/util/xmodem.py

R1719: The if expression can be replaced with 'test' (simplifiable-if-expression)
R1705: Unnecessary "else" after "return" (no-else-return)
C0103: Attribute name "__atCommand" doesn't conform to snake_case naming style (invalid-name)
R1719: The if expression can be replaced with 'test' (simplifiable-if-expression)
R0205: Class 'XBee16BitAddress' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
C0325: Unnecessary parens after 'not' keyword (superfluous-parens)
C0303: Trailing whitespace (trailing-whitespace)
W0311: Bad indentation. Found 20 spaces, expected 16 (bad-indentation)
C0330: Wrong continued indentation (add 1 space)
W0107: Unnecessary pass statement (unnecessary-pass)
Signed-off-by: Tatiana Leon <tatiana.leon@digi.com>

pylint: fix several pylint issues

---

digi/xbee/devices.py
digi/xbee/filesystem.py
digi/xbee/firmware.py
digi/xbee/models/zdo.py
digi/xbee/profile.py

New optional argument 'apply' for methods:
* `get_parameter()`
* `set_parameter()`
* `execute_parameter()`
This way internal executions can just use it and do not need to read the general apply flag (`is_apply_changes_enabled()`) to update it (`enable_apply_changes()`) and then restore the original value.
Default value for `apply` is `None` to keep the behaviour the method had in previous versions.

get: set: execute: add a new optional arg to set/get/execute parameter methods

---

digi/xbee/devices.py

When a Zigbee local node is updated to be a DigiMesh node, its 16-bit address
is not reset although its information is forced to be re-initalized. This
commit forces the 16-bit address to be 0xFFFE (unknown) for any protocol not
supporting 16-bit addressing.
Related to cc685b12eae508714703ac804d8584b9035ca0bd
https://jira.digi.com/browse/XNM-87

refresh: digimesh: reset 16-bit address for protocols that does not support it

---

digi/xbee/devices.py
digi/xbee/filesystem.py
digi/xbee/firmware.py
digi/xbee/io.py
digi/xbee/models/atcomm.py
digi/xbee/models/filesystem.py
digi/xbee/models/zdo.py
digi/xbee/packets/cellular.py
digi/xbee/packets/common.py
digi/xbee/packets/devicecloud.py
digi/xbee/packets/socket.py
digi/xbee/profile.py
digi/xbee/reader.py
digi/xbee/recovery.py
digi/xbee/sender.py
digi/xbee/util/xmodem.py

When encode or decode using utf-8 encoding avoid any 'UnicodeError' just
ignore the malformed data.
Malformed data may be received for example when working in DigiMesh encrypted.
If 2 nodes used different encryption keys (KY) data is received corrupted since
the receiver is unencrypting with the wrong key. This data may not be utf-8 in
fields that are expected to be, for example the AT command of a Remote AT
Command frame.
https://jira.digi.com/browse/XBHAWKDM-901

encoding: use utf-8 to encode/decode and ignore malformed data

---

digi/xbee/firmware.py
digi/xbee/models/atcomm.py

* Zigbee:
* Version 1009 and prior: only the GBL file is sent over the air
* Version 1009 and prior: delayed ACK for some packets
The Query Next Image Response and the final Image Block Response both cause the client to perform a long operation (erasing/verifying OTA update data in the storage slot) On these versions, the network ACK for the transmission is not sent until after this operation completes.
* Version 1008 and prior: recovering from failed client transmissions
Client (remote) does not retry requests. If the server (local) does not receive a request from the client, the server should proceed and send the next response, as though it had received the expected client request.
More than 3 client requests lost in a row is considered as a failure.
* Version 1007 and prior: OTA …

firmware update: ota: implement considerations for versions lower than 1009

---

digi/xbee/filesystem.py

Firmwares 100D (Zigbee), 200D (802.15.4), and 300D (DigiMesh) were released and none include files system API support.
This commit updates:
* The minimum firmware version with file system API support to 10FF (Zigbee), 20FF(802.15.4), and 30FF (DigiMesh).
* The maximum firmware version with file system OTA support to 10FF (Zigbee), 20FF(802.15.4), and 30FF (DigiMesh).
These minimum and maximum values must be updated when file sytem API support is added to the firmware (minimum value) or when file system OTA support is deprecated (maximum value)

filesystem: update min fw with fs API support and max with fs ota support

---

digi/xbee/devices.py

Only check if parent is initialized in end devices.

devices: fix is_device_info_complete() method of RemoteZigBeeDevice

---

CHANGELOG.rst
digi/xbee/filesystem.py
digi/xbee/firmware.py
digi/xbee/models/hw.py
digi/xbee/models/protocol.py
digi/xbee/profile.py
digi/xbee/recovery.py

- 0x4E: XBee 3 Cellular LTE-M/NB-IoT (Telit)
- 0x50: XB3-DMLR
- 0x51: XB3-DMLR868
- 0x52: XBee 3 Reduced RAM
- 0x53: S2C P5
https://onedigi.atlassian.net/browse/XBJAPI-535
Signed-off-by: Diego Escalona <diego.escalona@digi.com>

hardware: add new versions to the supported hardware list

---

CHANGELOG.rst
digi/xbee/comm_interface.py
digi/xbee/devices.py
digi/xbee/models/statistics.py
digi/xbee/packets/base.py
digi/xbee/packets/common.py
digi/xbee/packets/raw.py
digi/xbee/packets/wifi.py
digi/xbee/sender.py
doc/api/digi.xbee.models.statistics.rst
doc/examples.rst
doc/user_doc/communicating_with_xbee_devices.rst
examples/statistics/GetXBeeStatisticsSample/GetXBeeStatisticsSample.py
examples/statistics/GetXBeeStatisticsSample/readme.txt

Initial support to report basic XBee statistics:
* TX/RX packets
* TX/RX Bytes
* Remote AT command errors
* TX errors
This commit also updates the documentation and adds a basic example.

devices: add support for XBee statistics

---

CHANGELOG.rst
digi/xbee/devices.py
doc/user_doc/communicating_with_xbee_devices.rst
doc/user_doc/working_with_xbee_classes.rst

XBee 3 802.15.4 modules allows to send and receive explicit data (other module
hardware does not include this feature, i. e., S2C)
This commits includes methods to read and send explicit data to the 'XBeeDevice'
class so they are inherited by 'Raw802Device'. It removes the equivalent methods
from 'ZigBeeDevice', 'DigiMeshDevice', and 'DigiPointDevice' classes since now
they are defined in the super class. It also overrides the methods in the
'IPDevice' class so they throw an exception if used as they are not supported
for Cellular nor Wi-Fi XBee modules.
The related documentation is also updated.
https://onedigi.atlassian.net/browse/DAL-6334
Signed-off-by: Tatiana Leon <Tatiana.Leon@digi.com>

explicit data: add explicit data to 802.15.4

---

CHANGELOG.rst
digi/xbee/devices.py

'Create Source Route' packet (0x21) must include the hops to a destination node
from closest node to destination to closest neighbor to source. See:
https://www.digi.com/resources/documentation/digidocs/90001539/#reference/r_frame_0x21.htm
https://github.com/digidotcom/xbee-python/issues/278

zigbee: source route: reverse hops order for a 'Create Source Route' packet

---

digi/xbee/firmware.py
digi/xbee/models/protocol.py

If firmware XML contains a 'skip' region code, do not check the region code of the device before programming the firmware.
https://onedigi.atlassian.net/browse/XBPL-394

firmware: do not check the region for skip code

---

digi/xbee/firmware.py

This finally block assumed that target was always an XBeeDevice, while all of the code above it did the right thing and properly handled the case of it being a str.
Without this fix, performing a local update using a serial port argument will error out here with
AttributeError: 'str' object has no attribute '_active_update_type'

firmware: fix AttributeError when update_local_firmware is called with a string

---

CHANGELOG.rst
digi/xbee/devices.py
digi/xbee/util/srp.py
doc/api/digi.xbee.util.rst
doc/api/digi.xbee.util.srp.rst
doc/faq.rst
doc/index.rst
requirements.txt
setup.py

`pysrp` library includes 2 modules to implement SRP:
* _ctsrp: Using OS libraries to implement SRP.
* _pysrp: Pure Python implementation of SRP.
The first option is always `_ctsrp`. If there is any problem loading the required libraries or looking for required methods inside, `_pysrp` is loaded. This last module, `_pysrp` has a bug in the generation of the verifier for certain combination of username and password (for example, user=apiservice, password=1257c) See https://github.com/cocagne/pysrp/issues/55.
This commit removes the dependency to `pysrp` to avoid this bug and includes the required implementation to calculate a salt and the corresponding verifier to configure XBee Bluetooth password.

srp: remove 'pysrp' dependency

---

CHANGELOG.rst
digi/xbee/ble.py
digi/xbee/devices.py
digi/xbee/filesystem.py
digi/xbee/firmware.py
digi/xbee/models/address.py
digi/xbee/models/hw.py
digi/xbee/models/message.py
digi/xbee/models/protocol.py
digi/xbee/models/status.py
digi/xbee/packets/aft.py
digi/xbee/packets/base.py
digi/xbee/packets/bluetooth.py
digi/xbee/packets/factory.py
digi/xbee/reader.py
digi/xbee/recovery.py
doc/api/digi.xbee.ble.rst
doc/api/digi.xbee.packets.bluetooth.rst
doc/api/digi.xbee.packets.rst
doc/api/digi.xbee.rst
doc/examples.rst
doc/getting_started_with_xbee_python_library.rst
doc/user_doc/working_with_xbee_classes.rst
examples/communication/bluetooth/GapScanCursesDemo/GapScanCursesDemo.py
examples/communication/bluetooth/GapScanCursesDemo/readme.txt
examples/communication/bluetooth/GapScanExample/GapScanExample.py
examples/communication/bluetooth/GapScanExample/readme.txt
functional_tests/Bluetooth/device_info.py
functional_tests/Bluetooth/test_gap_scan.py

This product does not support the XBee protocol, but instead, only supports Bluetooth/BLE.
The XBee BLU currently adds extra support over the existing Bluetooth support, by adding a few new API packet/frames.
These frames are:
Bluetooth GAP Scan Request - 0x34
Bluetooth GAP Scan Legacy Advertisement Response - 0xB4 Bluetooth GAP Scan Extended Advertisement Response - 0xB7 Bluetooth GAP Scan Status - 0xB5
In addition to creating a new device type called BluDevice that supports these new calls, there have also been a couple new functional tests to verify the support, along with a new Demo/Example application that will initiate a BLE GAP scan, and display all devices that are broadcasting BLE advertisements.

Add support for the new XBee BLU device/product

---

digi/xbee/devices.py

Only remove our internal callbacks to listen for incoming route data if there are no more subscribed client callbacks.
https://onedigi.atlassian.net/browse/XNM-91

zigbee: route record: ensure internal route callbacks removed if no client callbacks
