digi/xbee/packets/base.py, digi/xbee/reader.py
=> fix #7: fix a bug when working in API escaped mode

digi/xbee/reader.py
Per our documentation [here](https://www.digi.com/resources/documentation/Digidocs/90001942-13/concepts/c_api_escaped_operating_mode.htm?TocPath=XBee%20API%20mode%7COperating%20mode%20configuration%7C_____1):
> API 2 mode guarantees all the 0x7E bytes received are start delimiters: this character cannot be part of any of the other frame fields (length, data, or checksum) since it must be escaped.
Prior to this change, the library assumes that the checksum byte is _not_ escaped.
=> fix #13: handle the case where the checksum byte is escaped when working in API escaped mode

digi/xbee/io.py
Signed-off-by: Héctor González <hector.gonzalez@digi.com>
=> io: change visibility of io sample parser methods to private

digi/xbee/packets/common.py, digi/xbee/packets/wifi.py
packets: fix several issues in the RemoteATCommandResponsePacket,
TransmitPacket, IODataSampleRxIndicatorPacket and
IODataSampleRxIndicatorWifiPacket classes
=> Minor fixes in packets

digi/xbee/devices.py, digi/xbee/packets/base.py, digi/xbee/reader.py
Important fixes related to how the callbacks are being executed.
=> Callback mechanism fixes

digi/xbee/devices.py, digi/xbee/util/utils.py, doc/user_doc/configuring_the_xbee_device.rst, requirements.txt
- enable_bluetooth()
- disable_bluetooth()
- get_bluetooth_mac_addr()
- update_bluetooth_password(String)
Added also a new chapter in the documentation explaining these new methods.
=> ble: add several methods related to the Bluetooth interface

examples/communication/bluetooth/ReceiveBluetoothFileSample/ReceiveBluetoothFileSample.py, examples/communication/bluetooth/ReceiveBluetoothFileSample/readme.txt
This example is used in conjunction with the 'XBee BLE Microcontroller'
example of the Mobile SDK.
=> examples: add new example to receive a file from the Bluetooth interface

digi/xbee/models/address.py
This commit also fixes inconsistencies between the 3 addresses.
=> address: add 'is_valid()' method to the 16, 64, and IMEI addresses

functional_tests/configuration/reset.py, functional_tests/long_test.py, functional_tests/network/discover_network.py
Signed-off-by: Tatiana Leon <tatiana.leon@digi.com>
=> functional test: remove the added callbacks before exiting

digi/xbee/devices.py, digi/xbee/models/atcomm.py, digi/xbee/models/status.py, digi/xbee/models/zdo.py, digi/xbee/packets/common.py
Complete full scan for 802.15.4 and DigiMesh protocols.
https://jira.digi.com/browse/XBPL-318
https://jira.digi.com/browse/XCTUNG-376
=> network full scan: 802.15.4 and DigiMesh

digi/xbee/devices.py, digi/xbee/reader.py
When setting and getting parameters using AT commands (local or remote) get
all the information to create a new node or update the existing one in the
network
* When receiving an AT Command Response (0x88) or Remote AT Command
Response (0x97), check if the answer is for commands 'NI', 'VR', or 'HV'
to create a new node with that info or update the existing in the network.
* When sending an AT Command (0x08) or Remote AT Command (0x17) to configure
parameters 'NI' or 'MY', also use that value to update an existing node.
https://jira.digi.com/browse/XBPL-336
=> init XBee: get all the info from sent/received AT Command frames (local/remote)

README.rst
Signed-off-by: Jose Diaz de Grenu <Jose.DiazdeGrenu@digi.com>
=> README: fix documentation URL

digi/xbee/devices.py, digi/xbee/packets/aft.py, digi/xbee/packets/base.py, digi/xbee/packets/zigbee.py
https://jira.digi.com/browse/XNM-2
=> zigbee: source route: create source routes for Zigbee nodes

digi/xbee/firmware.py
On XBee 3 ZB remote firmware update after sending the explicit frame
with the 'Upgrade end response' command, the received transmit status
has an 'Address not found' error (0x24).
=> firmware: workaround for 'Address not found' error on remote fw update

digi/xbee/profile.py
Signed-off-by: David Escalona <david.escalona@digi.com>
=> profile: fix string format TypError when raising exception

digi/xbee/devices.py
Signed-off-by: Jose Diaz de Grenu <Jose.DiazdeGrenu@digi.com>
=> devices: update FW and HW versions also

digi/xbee/devices.py
https://jira.digi.com/browse/DAL-2791
=> devices: expand execute command to accept an argument

digi/xbee/devices.py, digi/xbee/util/exportutils.py
The result is a '*.xnet' file compatible with the XBee Network Assistant.
https://jira.digi.com/browse/DAL-4398
=> network: add support to export an XBee network

digi/xbee/models/zdo.py
Commit that introduce the issue 880ab5ef5dfbfdbd1c56af6c652d3852e88479dc
https://github.com/digidotcom/xbee-python/issues/122
=> digimesh: find neighbors: fix attribute name in debug message

CHANGELOG.rst
Signed-off-by: David Escalona <david.escalona@digi.com>
=> changelog: prepare changelog for 1.4.1 release

CHANGELOG.rst, digi/xbee/models/hw.py, digi/xbee/models/protocol.py
- 0x54: XBee 3 Cellular Global LTE Cat 1
- 0x55: XBee 3 Cellular North America LTE Cat 1
https://onedigi.atlassian.net/browse/XBPL-381
=> hardware: add new versions to the supported hardware list

digi/xbee/filesystem.py
- Cellular devices do not have NP setting, so the default block size for them should be 1490.
- It's not possible to specify a write offset when uploading secure files, 0xFFFFFFFF (use current position) must be used.
- Cellular devices return a file size of 0 bytes when creating a new file.
- When uploading files bigger than the block size, the last offset must be used. Otherwise, the file is overwritten at offset 0.
=> filesystem: several fixes in the API file system for Cellular devices

doc/user_doc/communicating_with_xbee_devices.rst
https://onedigi.atlassian.net/browse/XBPL-424
=> doc: fix some methods signature

CHANGELOG.rst, digi/xbee/devices.py, digi/xbee/filesystem.py, digi/xbee/models/hw.py, digi/xbee/models/protocol.py, digi/xbee/packets/aft.py, digi/xbee/packets/factory.py, digi/xbee/packets/socket.py, digi/xbee/reader.py, digi/xbee/sender.py, digi/xbee/xsocket.py
Adds preliminary support for XBee Wi-SUN, and IPv6 addressing in the library.
=> XBee Wi-SUN support
